.NET 9 target
SebastianStehle/mjml-net pull request #211
Opened 2024-12-30 10:31 UTC by SPWizard01

Updated dependencies and added .NET 9 target
Addresses #208

2025-01-01 20:16 UTC, SebastianStehle requested changes

2025-01-01 20:16 UTC, SebastianStehle commented on Mjml.Net/Mjml.Net.csproj
> +    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.0" />
Can we have a multi target here?

2025-01-07 18:13 UTC, SPWizard01 commented on Mjml.Net/Mjml.Net.csproj
> +    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.0" />
I think the change should work now, although not sure if you want to target v8 for anything less than .net 9

2025-01-08 07:57 UTC, SebastianStehle commented
Seems the build also needs an update

2025-01-08 09:20 UTC, merged