mj-navbar
SebastianStehle/mjml-net pull request #80
Opened 2022-03-20 21:03 UTC by SebastianStehle

2022-03-20 21:14 UTC, SebastianStehle commented
mj-navbar is done, but the navbar-links are pending.

2022-03-20 21:14 UTC, LiamRiddell requested changes

2022-03-20 21:14 UTC, LiamRiddell commented on Mjml.Net/Components/Body/NavbarComponent.cs
> +            context.SetGlobalData("mj-image", new Style(HeadStyle));
Should this be `mj-image`?

2022-03-20 21:17 UTC, SebastianStehle commented on Mjml.Net/Components/Body/NavbarComponent.cs
> +            context.SetGlobalData("mj-image", new Style(HeadStyle));
True :D

2022-03-20 21:20 UTC, LiamRiddell approved these changes

2022-03-21 10:31 UTC, LiamRiddell approved these changes

2022-03-21 10:31 UTC, LiamRiddell commented
It looks really good, nice work :)

2022-03-21 10:54 UTC, SebastianStehle commented
It is so easy with all the code generators now.

2022-03-21 10:55 UTC, merged